title: "3615 MON BLOG"
description: "Journaliste · Scripts de veille · Données publiques"
theme: minima
lang: fr
author: "Votre Nom"
email: "votre@email.com"
github_username: VOTRE_PSEUDO

minima:
  skin: dark

show_excerpts: true
